# Generated by Django 3.2 on 2021-04-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_todo_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_to',
            new_name='created',
        ),
    ]
